Word_1: "*NODE"
Word_2: "*ELEMENT"
Word_3: "Fixed"
Word_4: "Point_A"
Word_5: "Point_O"
Word_6: "Fixed_001"
Word_7: "Fixed_010"
Word_8: "Fixed_011"
Word_9: "Fixed_100"
Word_10: "Fixed_101"
Word_11: "Fixed_110"
